# Generated by Django 4.2.18 on 2025-02-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
    ]
