# Generated by Django 4.2.18 on 2025-02-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('em_desenvolvimento', 'Em desenvolvimento'), ('aguardando_cliente', 'Aguardando cliente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('cancelado', 'Cancelado')], default='em_desenvolvimento', max_length=20),
        ),
    ]
